languageCode: en-us
title: Design System Template
copyright: Template Footer
pluralizelisttitles: false
markup:
  goldmark:
    renderer:
      Unsafe: true
params:
  appleScope: ""
  audience: ""
  logo: /media/images/logo.png
  scope: ""
sectionPagesMenu: ""
menu:
  Main:
  - identifier: Introduction
    name: Introduction
    url: /
    weight: 1
  - identifier: Design Principles
    name: Design Principles
    url: /design-principles/
    weight: 2
  - identifier: Visual Elements
    name: Visual Elements
    url: /visual-elements/
    weight: 3
  - identifier: Typography
    name: Typography
    url: /typography/
    weight: 4
  - identifier: Components
    name: Components
    url: /components/
    weight: 5
  - identifier: Motion
    name: Motion
    url: /motion/
    weight: 6
  - identifier: Design Tokens
    name: Design Tokens
    url: /design-tokens/
    weight: 7
  - identifier: Resources
    name: Resources
    url: /resources/
    weight: 8
  - identifier: Accessibility
    name: Accessibility
    url: /accessibility/
    weight: 9
  - identifier: Contributing
    name: Contributing
    url: /contributing/
    weight: 10
  - identifier: Reference
    name: Reference
    url: /reference/
    weight: 11
  - identifier: FAQs
    name: FAQs
    url: /faqs/
    weight: 12
  - identifier: Updates
    name: Updates
    url: /updates/
    weight: 13
outputFormats:
  MenuIndex:
    baseName: menu
    mediaType: application/json
  SearchMap:
    baseName: searchmap
    mediaType: application/json
outputs:
  home:
  - HTML
  - RSS
  - MenuIndex
  - SearchMap
module:
  imports:
  - path: github.com/spandigital/presidium-theme-website
    disabled: false
  - path: github.com/spandigital/presidium-theme-pdf
    disabled: true
enableInlineShortcodes: true
frontmatter:
  lastmod:
  - lastmod
  - :fileModTime
  - :default
